model:
  type: FR_UNet
  args:
    {}
# loss: BCELoss, CE_DiceLoss, Soft_clDice, DiceLoss, 
loss:
  type: DiceLoss
  args:
    {}

dataset:
  type: FIVES
  path: ./datasets/FIVES
  args:
    {}
  
optimizer:
  type: Adam
  args:
    lr: 1e-4
    weight_decay: 1e-5

lr_scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 40
    
# Data config
size: 2048
batch_size: 1
random_seed: 23
num_workers: 8
epochs: 200
save_dir: ./model_results/FR_UNet/
val_per_epochs: 1
save_period: 5

tensorboard: true
threshold: 0.5
threshold_low: 0.3
DTI: false
amp: true # automatic mixed precision
tta: false
CCC: false